spring.application.name=workforce-continuity-system

server.port=${PORT:8080}

# CORS
spring.web.cors.allowed-origins=http://localhost:5173,http://localhost:5174,https://remarkable-meerkat-736905.netlify.app
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*